BEGIN;

CREATE TABLE IF NOT EXISTS tags (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name character varying NOT NULL,
  slug character varying NOT NULL,
  updated_at timestamp(3) with time zone NOT NULL DEFAULT now(),
  created_at timestamp(3) with time zone NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS tags_name_idx ON tags (name);
CREATE UNIQUE INDEX IF NOT EXISTS tags_slug_idx ON tags (slug);
CREATE INDEX IF NOT EXISTS tags_created_at_idx ON tags (created_at);
CREATE INDEX IF NOT EXISTS tags_updated_at_idx ON tags (updated_at);

ALTER TABLE pages_rels ADD COLUMN IF NOT EXISTS tags_id integer;
CREATE INDEX IF NOT EXISTS pages_rels_tags_id_idx ON pages_rels (tags_id);
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE constraint_name = 'pages_rels_tags_fk'
      AND table_name = 'pages_rels'
  ) THEN
    ALTER TABLE pages_rels
      ADD CONSTRAINT pages_rels_tags_fk FOREIGN KEY (tags_id) REFERENCES tags(id) ON DELETE CASCADE;
  END IF;
END$$;

ALTER TABLE payload_locked_documents_rels ADD COLUMN IF NOT EXISTS tags_id integer;
CREATE INDEX IF NOT EXISTS payload_locked_documents_rels_tags_id_idx ON payload_locked_documents_rels (tags_id);
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE constraint_name = 'payload_locked_documents_rels_tags_fk'
      AND table_name = 'payload_locked_documents_rels'
  ) THEN
    ALTER TABLE payload_locked_documents_rels
      ADD CONSTRAINT payload_locked_documents_rels_tags_fk FOREIGN KEY (tags_id) REFERENCES tags(id) ON DELETE CASCADE;
  END IF;
END$$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name = 'pages_tags'
  ) THEN
    INSERT INTO tags (name, slug)
    SELECT DISTINCT pt.tag,
      trim(both '-' from regexp_replace(lower(pt.tag), '[^a-z0-9]+', '-', 'g'))
    FROM pages_tags pt
    WHERE pt.tag IS NOT NULL
      AND btrim(pt.tag) <> ''
    ON CONFLICT (name) DO NOTHING;

    INSERT INTO pages_rels ("order", parent_id, path, tags_id)
    SELECT pt._order, pt._parent_id, 'tags', t.id
    FROM pages_tags pt
    JOIN tags t ON t.name = pt.tag
    LEFT JOIN pages_rels pr
      ON pr.parent_id = pt._parent_id
     AND pr.path = 'tags'
     AND pr.tags_id = t.id
    WHERE pr.id IS NULL;
  END IF;
END$$;

COMMIT;
